### ISSUE TITLE
Llama 3.1 405B Cannot Run on 8*A100

### ISSUE THREAD

**Issue by kangqi-ni** [huggingface/huggingface-llama-recipes#21]
I am trying to run Llama 3.1 405B with fp8 quantization on 8-A100. There is a note saying that "running the FP8 model requires GPUs with compute capability > 9. A potential working setup would be 8 H100." But since I do not have H100, I tried a 8-A100 setup and received "ValueError: FP8 quantized models is only supported on GPUs with compute capability >= 9.0 (e.g H100)." Is there a way to run Llama 3.1 405B fp8 on 8-A100?

**Comment by pcuenca** [comment]
Hi @kangqi-ni! This is a hardware limitation. Unlike the H100, the A100 [does not have FP8 tensor cores](https://www.nvidia.com/content/dam/en-zz/Solutions/Data-Center/a100/pdf/nvidia-a100-datasheet-nvidia-us-2188504-web.pdf). Could you maybe want to try one of the INT4 versions instead?

**Comment by ariG23498** [comment]
Hey @kangqi-ni 

I am closing the issue due to it being stale. Please feel free to ask me to reopen it if you encounter further problems.
