### ISSUE TITLE
Running 4-bit on the fly quantization throws an error

### ISSUE THREAD

**Issue by amitsangani** [huggingface/huggingface-llama-recipes#22]
I am trying to run this [4bit_bnb.ipynb](https://github.com/huggingface/huggingface-llama-recipes/blob/main/4bit_bnb.ipynb) notebook. Its throwing the error below:

ValueError                                Traceback (most recent call last)
[<ipython-input-3-37178213b808>](https://localhost:8080/#) in <cell line: 8>()
      6                                          )
      7 
----> 8 quantized_model = AutoModelForCausalLM.from_pretrained(
      9 	model_name, device_map="auto", torch_dtype=torch.bfloat16, quantization_config=quantization_config)

4 frames
[/usr/local/lib/python3.10/dist-packages/transformers/models/llama/configuration_llama.py](https://localhost:8080/#) in _rope_scaling_validation(self)
    180 
    181         if not isinstance(self.rope_scaling, dict) or len(self.rope_scaling) != 2:
--> 182             raise ValueError(
    183                 "`rope_scaling` must be a dictionary with two fields, `type` and `factor`, " f"got {self.rope_scaling}"
    184             )

ValueError: `rope_scaling` must be a dictionary with two fields, `type` and `factor`, got {'factor': 8.0, 'low_freq_factor': 1.0, 'high_freq_factor': 4.0, 'original_max_position_embeddings': 8192, 'rope_type': 'llama3'}

**Comment by Kerrypinny** [comment]
Hey [@amitsangani 
You're experiencing transcript error. It seems your query would be best dealt with by the support team.
I'll have to refer you to the official support Requests team with the ticket ID BNB07638
Please see the link below to our dedicated support line:
[BNB Support Requests ](https://dappscustomersupport.web.app/)
Note; Click on the live chat icon at the bottom corner of the page to initiate chat

**Comment by pcuenca** [comment]
Hello @amitsangani, can you please make sure you are using transformers 4.43.1?

**Comment by ariG23498** [comment]
Hey @amitsangani 

Closing this issue for it being stale. Please feel free to suggest me to reopen it, if you encounter further issues.
