### ISSUE TITLE
Running Llama 3.1 405B H100 Multi-Node

### ISSUE THREAD

**Issue by Pedrexus** [huggingface/huggingface-llama-recipes#26]
Hello all,

I am trying to execute llama on a H100 GPU server, but the system uses openmpi and gives me only a single gpu per node.
I never worked with this scenario before, how could I adapt https://github.com/huggingface/huggingface-llama-recipes/blob/main/fp8-405B.ipynb, for example, for simple inference?

thanks as always for the great work!

**Comment by ariG23498** [comment]
Hey @Pedrexus 

> and gives me only a single gpu per node

Unfortunately this is a hardware specific problem and not something we can help you with. You can however spin up a cluster with [Hugging Face spaces](https://huggingface.co/blog/spaces-dev-mode), and try to run the code.

Closing this issue.
