### ISSUE TITLE
Serve Llama models with `Text Generation Inference` recipe

### ISSUE THREAD

**Issue by sergiopaniego** [huggingface/huggingface-llama-recipes#45]
This issue comes from the open call for contributions #43.

In this case, this issue is intended for the generation of a recipe for serving Llama models using the [Text Generation Inference](https://huggingface.co/docs/text-generation-inference/en/index)

**Comment by ariG23498** [comment]
Hi @sergiopaniego 
Thank you for taking this up!

Looking forward to what you build.

**Comment by kritikaparmar-programmer** [comment]
Hey @sergiopaniego , are you looking for collaborators? I would like to contribute to this project. Thankyou

**Comment by sergiopaniego** [comment]
Hi @kritikaparmar-programmer!

Thanks for your interest. I've created the PR with the recipe. You may take a look at it and see if anything may be improved 😄
