### ISSUE TITLE
Implementing RAG with Llama

### ISSUE THREAD

**Issue by Purity-E** [huggingface/huggingface-llama-recipes#51]
Thanks for the [Open call to contribute](https://github.com/huggingface/huggingface-llama-recipes/issues/43)

My project of interest is Implement Retrieval Augmented Generation with Llama
Here's my approach:
- Implement RAG by trying out the different retrieval methods such as BM25, dense retrieval
- Evaluating and monitoring the RAG system

I'm looking forward to hear your thoughts and suggestion on this.

**Comment by ariG23498** [comment]
Hey @Purity-E

Thank you for the proposal. While this is a great proposal, this does not fall into the realm of what we are looking for in this repository. We would love to have a very simple RAG pipeline with the Llama family of models.

I would have to close this issue, but feel free to look into #47 if you wanted to collaborate with the OP.

**Comment by Purity-E** [comment]
Okay
