### ISSUE TITLE
LLaMA Guard for prompt adjustments for Image Generation models

### ISSUE THREAD

**Issue by Sakalya100** [huggingface/huggingface-llama-recipes#54]
Hello 👋 

This issue is for #43 

I am creating this issue to demonstrate a use case of Llama Guard in filtering and auto-adjusting prompts for safe input in image generation models. I will be using the https://huggingface.co/meta-llama/Llama-Guard-3-1B model. 

We can also extend this to image-to-text generation applications using the vision model for llama guard.

I am eager to hear your thoughts and suggestions on this!!

**Comment by ariG23498** [comment]
Hey @Sakalya100 

We already have an ongoing issue on Llama Guard (#53)

It would be beneficial for you to comment your ideas there (or even suggest changes and work with the OP). WDYT?

**Comment by Sakalya100** [comment]
Hey @ariG23498 

Sure. I saw the issue you referred and I think I can work alongside to get this integrated. I will add my ideas there and start working on it.

Thanks
