### ISSUE TITLE
Simple RAG App using Llama 3

### ISSUE THREAD

**Issue by emre570** [huggingface/huggingface-llama-recipes#61]
Hello folks, I can build a simple RAG app using FAISS, Ollama, Streamlit and Llama 3. If this suits for llama-recipes, I'm happy to work.

The project is ready to use in my repository [here](https://github.com/emre570/simple-rag-app).

Thanks.

**Comment by ariG23498** [comment]
Hey @emre570 

Thank you for the issue. We are unfortunately not looking for an end to end solution in this repository. We would like to have a very simple pipeline for RAG with the Hugging Face ecosystem.

#47 already takes a stab at it. I am closing this issue for the time being. Please feel free to suggest any other proposals that you might have!
