### ISSUE TITLE
Simple RAG Pipeline

### ISSUE THREAD

**Issue by atharv-jiwane** [huggingface/huggingface-llama-recipes#62]
Hey @ariG23498 thanks for the Call for Contributions on #43 .
I was looking to contribute to one of the issues here and build a simple RAG pipeline using the LLaMa family of models and then improve the pipeline by adding further enhancements, 

Thanks,
Issue #62

**Comment by ariG23498** [comment]
Hey @atharv-jiwane 

Unfortunately this has already been taken #47 

Feel free to connect to the OP there. Closing this issue. Please feel free to suggest something else on a new issue.
