### ISSUE TITLE
Proposal for contribution: Prompt engineering for structured output

### ISSUE THREAD

**Issue by TensorCruncher** [huggingface/huggingface-llama-recipes#71]
Hello everyone

**Proposal:**  
A Pokédex for DSA problems. You give a problem statement as input and get a predetermined set of information such as:

- Data structures needed
- Patterns
- Difficulty level
- Space time complexity
- A natural language description of how to approach the problem, possibly multiple short descriptions of different approaches.

**Why it fits:** 
This would be a simple notebook, and I could make a gradio demo out of it. It highlights using prompt engineering to get consistent structured output from the LLM. Also, very useful for a large number of aspiring and existing developers!

Please let me know if this would be a good fit. I am new to open source and HF, so would love for all forms of feedback.

If this is not a good fit, please let me know a better direction or if this idea can be better adapted in any way.

**Comment by ariG23498** [comment]
Hey @TensorCruncher 

Could you create a quick colab notebook and share it in the issues for me to look at it?

I like the idea, but I am not very sure if the idea fits the repository. If I could take a look at the colab notebook, it would be easier for me give you quick feedback.

How does that sound?

**Comment by TensorCruncher** [comment]
@ariG23498 That sounds like a great idea, i'll get right to it.

**Comment by TensorCruncher** [comment]
Hey @ariG23498,

I tried making the notebook but it turns out that it's quite difficult to get the LLM to respond in exactly the format I wanted. I imagine it would have to be fine tuned on a dataset with many more examples to get it to follow the exact output structure I had in mind.

I'm requesting you to close this issue.

Thank you for the opportunity to contribute though, I learned a whole bunch!

**Comment by ariG23498** [comment]
While I am closing this issue, but I am very proud of you as a person to be bold enough to admit something was not working as expected and come to a decision of closing this contribution issue.

I would be happy to help you in some other issue later. Thank you!
